
#Область include_IntegrationBlockly_base_Blocks_ExtsysRead
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_C1RefToObj
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_C1RefFromId
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_SabyUploadFiles
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_SabyConvertFilesToPdf
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_C1DocReadPrintForms
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_NewObj
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_GetCurrentDatetime
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ObjPropSet
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_Format 
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ObjPropGet
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_C1CallSelect 
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_C1Ref
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_C1Predefine  
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_C1RefFromAPI3  
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_C1MetaRead 
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_C1MetaCreate
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_C1MetaUpdate
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_C1RegisterUpdate
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_C1Strip 
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ReSearch 
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_textCharAt
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_textIndexOft
#КонецОбласти

#Область include_IntegrationBlockly_src_Blocks_ListObjGroup 
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_Uuid4
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_MathRound 
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_SabyEdoStart
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_Saby
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_C1CallFilter
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_C1ClearTable 
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_C1GetUuid
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_SabyExecuteAction
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_SabyFind
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_SabyGet
#КонецОбласти

#Область include_BlocklyExecutor_base_Blocks_LogicNegate
#КонецОбласти

#Область include_BlocklyExecutor_base_Blocks_textGetSubstring
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ObjPropAppend
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ExtsyncdocWrite
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ExtsyncdocCreate
#КонецОбласти

#Область include_IntegrationBlockly_base_TestGetSabyObject
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_FedConvertObjectToXml
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_FedConvertXmlToObject 
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ExtsyncdocRun
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ExtsysUpdateStatus
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_SabyExtsyncobjList
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_SabyTaskList
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_AccountingEntriesList
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_AccountingEntriesList2
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_SabyReadChanges
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_SabyReadDocument
#КонецОбласти 

#Область include_IntegrationBlockly_base_Blocks_SabyWriteDocument
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_C1AttachAttachment
#КонецОбласти  

#Область include_IntegrationBlockly_base_Blocks_C1Calculate
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_C1Execute2
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ExtSysReadChanges  
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ExtSyncDocFillChangedSbisObjects 
#КонецОбласти

#Область include_IntegrationBlockly_base_ПодготовитьСтруктуруПрогрессаВыпонения
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_IndicatorFromAccountingEntrySide
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ExtsysCalcIni
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_AccordionItem
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ObjActionListView
#КонецОбласти  

#Область include_IntegrationBlockly_base_Blocks_ObjActionListViewFilter
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ObjActionListViewColumn
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ObjActionListViewToolbar
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ObjActionListViewToolbarSearch
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ViewToolbarMenu
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ExecuteWorkspace
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_PublicParamGet
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_Try
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_RaiseExtException
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ExtsysPrintFormList
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ObjectGetAttachments
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ObjectGetAttachmentsEDO
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_AlgorithmInfo
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ConnectionPublicParamRead
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_ConnectionPublicParamUpdate
#КонецОбласти

